"""
CUSTOMS CARGO — Level Publisher
================================
Cách dùng:
  1. Đặt file level .json vào thư mục data/levels/
  2. Chạy: python3 publish_levels.py
  3. Script tự convert .json -> .js và cập nhật manifest.js
  4. Commit toàn bộ thư mục data/levels/ lên GitHub

Không cần cài thêm thư viện gì.
"""

import json
import os
import re
from pathlib import Path

LEVELS_DIR = Path(__file__).parent / "data" / "levels"
MANIFEST   = LEVELS_DIR / "manifest.js"

def slugify(name: str) -> str:
    """Convert level name/id to safe filename."""
    s = name.lower().strip()
    s = re.sub(r'[^\w\s-]', '', s)
    s = re.sub(r'[\s_-]+', '_', s)
    return s or "level"

def json_to_js(level_data: dict, var_name: str) -> str:
    return (
        f"// Level: {level_data.get('name', var_name)}\n"
        f"window.LEVEL_DATA['{var_name}'] = "
        + json.dumps(level_data, ensure_ascii=False, indent=2)
        + ";\n"
    )

def main():
    LEVELS_DIR.mkdir(parents=True, exist_ok=True)

    published = []

    # Process all .json files in data/levels/
    json_files = sorted(LEVELS_DIR.glob("*.json"))
    if not json_files:
        print("Không tìm thấy file .json nào trong data/levels/")
        print("Đặt file level .json vào thư mục đó rồi chạy lại script.")
        return

    for jf in json_files:
        with open(jf, encoding="utf-8") as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError as e:
                print(f"  ✗ Lỗi đọc {jf.name}: {e}")
                continue

        # Determine variable name from level id or filename
        level_id  = data.get("id") or jf.stem
        var_name  = slugify(level_id)

        js_file   = LEVELS_DIR / f"{var_name}.js"
        js_content = json_to_js(data, var_name)

        with open(js_file, "w", encoding="utf-8") as f:
            f.write(js_content)

        published.append(var_name)
        print(f"  ✓ {jf.name}  →  data/levels/{var_name}.js")

    # Update manifest.js
    manifest_content = (
        "// =====================================================================\n"
        "// CUSTOMS CARGO — Level Manifest (auto-generated by publish_levels.py)\n"
        "// =====================================================================\n"
        "window.LEVEL_MANIFEST = [\n"
        + "".join(f"  '{v}',\n" for v in published)
        + "];\n"
    )
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write(manifest_content)

    print(f"\n✅ manifest.js cập nhật với {len(published)} levels: {published}")
    print("\nBước tiếp theo:")
    print("  git add data/levels/")
    print("  git commit -m 'publish levels'")
    print("  git push")

if __name__ == "__main__":
    main()
